### ISSUE TITLE
Appli Avatar Tizen OS

### ISSUE THREAD

**Issue by Seb85** [Spikharpax/Avatar-Plugin-android#1]
Bonjour Stéphane,

Je suis un heureux possesseur de la montre galaxy watch depuis peu.

J'ai dans l'idée d'utiliser Avatar avec.

Bon par contre c'est pas de l'android mais Tizen OS.
J'aimerai développer une appli pour ce type de montre comme ton app android. La montre fait micro/haut parleur.
Je ne sais pas trop par ou commencer, je me disais que je pouvais peut être m'inspirer de ton appli. Tu pourrais stp me partager le développement sous android?

Merci pour ton aide

**Comment by Spikharpax** [comment]
Slt Seb,

Sympa :-) dommage que tu n'as pas acheté une apple watch, j'aurais aimé que tu développes un truc avec... :-)

Sinon, le truc c'est que ce que j'ai développé pour le plugin Androd est en Java.
Si tu ne connais pas, tu vas avoir super du mal. De plus, les libs utilisées ne te diront rien et ne pourront pas être utilisées.
Donc il faut que tu partes de 0.
Tizen OS en application web est du HTML 5 et javascript, donc super simple. J'espère pour toi que tu as un micro et de quoi faire du speechToText, ce serait le top...

Tu as heureusement un Tizen Studio qui va te mâcher le boulot.
Si tu as des questions, je pourrais peut être t'aider pour quelques solutions.
Bon courage
